/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/IRcEkJDmGYO
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function AtlasPO() {
  return (
    <div className="w-full max-w-2xl mx-auto p-6 space-y-6">
      <form className="grid gap-4">
        <div className="space-y-2">
          <Label htmlFor="po-number">PO Number</Label>
          <Input id="po-number" placeholder="Enter PO Number" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="files">Upload Files</Label>
          <Input id="files" type="file" multiple />
        </div>
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-medium">File Preview</h3>
            <div className="flex items-center gap-2">
              <UploadIcon className="w-5 h-5 text-primary" />
              <span className="text-primary">Uploaded Files</span>
            </div>
          </div>
          <div className="grid grid-cols-3 gap-4">
            <div className="bg-muted rounded-md overflow-hidden aspect-square">
              <img
                src="/placeholder.svg"
                alt="File Preview"
                width={200}
                height={200}
                className="object-cover w-full h-full"
                style={{ aspectRatio: "200/200", objectFit: "cover" }}
              />
            </div>
            <div className="bg-muted rounded-md overflow-hidden aspect-square">
              <img
                src="/placeholder.svg"
                alt="File Preview"
                width={200}
                height={200}
                className="object-cover w-full h-full"
                style={{ aspectRatio: "200/200", objectFit: "cover" }}
              />
            </div>
            <div className="bg-muted rounded-md overflow-hidden aspect-square">
              <img
                src="/placeholder.svg"
                alt="File Preview"
                width={200}
                height={200}
                className="object-cover w-full h-full"
                style={{ aspectRatio: "200/200", objectFit: "cover" }}
              />
            </div>
          </div>
        </div>
        <div className="space-y-2">
          <h3 className="text-lg font-medium">Uploaded Files</h3>
          <div className="overflow-x-auto">
            <table className="w-full text-left">
              <thead>
                <tr className="border-b">
                  <th className="p-3 font-medium">Filename</th>
                  <th className="p-3 font-medium">Size</th>
                  <th className="p-3 font-medium">Type</th>
                </tr>
              </thead>
              <tbody>
                <tr className="border-b">
                  <td className="p-3">example.pdf</td>
                  <td className="p-3">2.3 MB</td>
                  <td className="p-3">PDF</td>
                </tr>
                <tr className="border-b">
                  <td className="p-3">image.jpg</td>
                  <td className="p-3">1.5 MB</td>
                  <td className="p-3">JPEG</td>
                </tr>
                <tr className="border-b">
                  <td className="p-3">document.docx</td>
                  <td className="p-3">0.8 MB</td>
                  <td className="p-3">DOCX</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        <Button type="submit" className="ml-auto">
          Sync to Zoho
        </Button>
      </form>
    </div>
  )
}

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}
