/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kFMlO02G9j1
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { CartesianGrid, XAxis, Bar, BarChart, Line, LineChart } from "recharts"
import { ChartTooltipContent, ChartTooltip, ChartContainer } from "@/components/ui/chart"

export function MainDashboard() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground px-6 py-4 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2 font-bold text-xl" prefetch={false}>
          <DollarSignIcon className="h-6 w-6" />
          Finance Automation
        </Link>
        <nav className="flex items-center gap-4">
          <Link href="#" className="hover:underline" prefetch={false}>
            Features
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Integrations
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Pricing
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Contact
          </Link>
          <Button variant="outline">Sign In</Button>
          <Button>Sign Up</Button>
        </nav>
      </header>
      <main className="flex-1">
        <section className="bg-gradient-to-r from-primary to-primary-foreground text-primary-foreground py-20 px-6">
          <div className="max-w-4xl mx-auto text-center space-y-6">
            <h1 className="text-4xl font-bold">AI-Driven Finance Automation</h1>
            <p className="text-xl">Streamline your financial operations with our intelligent solution.</p>
            <div className="flex justify-center gap-4">
              <Button size="lg">Get Started</Button>
              <Button variant="outline" size="lg">
                Learn More
              </Button>
            </div>
          </div>
        </section>
        <section className="py-16 px-6">
          <div className="max-w-4xl mx-auto grid md:grid-cols-2 gap-12">
            <div>
              <h2 className="text-3xl font-bold mb-4">AI-based Data Extraction and Classification</h2>
              <p className="text-muted-foreground">
                Our advanced machine learning models automatically extract and categorize invoice data, saving you time
                and reducing errors.
              </p>
            </div>
            <div>
              <h2 className="text-3xl font-bold mb-4">Anomaly Detection</h2>
              <p className="text-muted-foreground">
                Identify and flag any suspicious or irregular financial transactions with our robust anomaly detection
                algorithms.
              </p>
            </div>
            <div>
              <h2 className="text-3xl font-bold mb-4">3rd Party Integrations</h2>
              <p className="text-muted-foreground">
                Seamlessly integrate with your favorite accounting, CRM, and productivity tools for a streamlined
                financial workflow.
              </p>
            </div>
            <div>
              <h2 className="text-3xl font-bold mb-4">Feedback Loop</h2>
              <p className="text-muted-foreground">
                Our solution continuously learns and improves through a feedback mechanism, ensuring accuracy and
                efficiency over time.
              </p>
            </div>
          </div>
        </section>
        <section className="bg-muted py-16 px-6">
          <div className="max-w-4xl mx-auto text-center space-y-6">
            <h2 className="text-3xl font-bold">Advanced Analytics and Reporting</h2>
            <p className="text-muted-foreground">
              Gain deeper insights into your financial data with our comprehensive analytics and reporting capabilities.
            </p>
            <BarchartChart className="aspect-[16/9]" />
          </div>
        </section>
        <section className="py-16 px-6">
          <div className="max-w-4xl mx-auto grid md:grid-cols-2 gap-12">
            <div>
              <h2 className="text-3xl font-bold mb-4">Trusted by Businesses</h2>
              <p className="text-muted-foreground">
                Our solution is trusted by businesses of all sizes to streamline their financial operations and make
                informed decisions.
              </p>
              <div className="grid grid-cols-3 gap-6 mt-8">
                <img
                  src="/placeholder.svg"
                  width={120}
                  height={60}
                  alt="Logo"
                  className="aspect-[2/1] object-contain"
                />
                <img
                  src="/placeholder.svg"
                  width={120}
                  height={60}
                  alt="Logo"
                  className="aspect-[2/1] object-contain"
                />
                <img
                  src="/placeholder.svg"
                  width={120}
                  height={60}
                  alt="Logo"
                  className="aspect-[2/1] object-contain"
                />
              </div>
            </div>
            <div>
              <h2 className="text-3xl font-bold mb-4">Get Started Today</h2>
              <p className="text-muted-foreground">
                Sign up for our Finance Automation Solution and take control of your financial data.
              </p>
              <form className="mt-8 space-y-4">
                <Input type="email" placeholder="Enter your email" />
                <Button type="submit" className="w-full">
                  Get Started
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground px-6 py-8">
        <div className="max-w-4xl mx-auto grid md:grid-cols-3 gap-8">
          <div>
            <h3 className="font-bold mb-2">Company</h3>
            <nav className="space-y-2">
              <Link href="#" className="hover:underline" prefetch={false}>
                About
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Team
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Careers
              </Link>
            </nav>
          </div>
          <div>
            <h3 className="font-bold mb-2">Product</h3>
            <nav className="space-y-2">
              <Link href="#" className="hover:underline" prefetch={false}>
                Features
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Integrations
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Pricing
              </Link>
            </nav>
          </div>
          <div>
            <h3 className="font-bold mb-2">Resources</h3>
            <nav className="space-y-2">
              <Link href="#" className="hover:underline" prefetch={false}>
                Blog
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Documentation
              </Link>
              <Link href="#" className="hover:underline" prefetch={false}>
                Support
              </Link>
            </nav>
          </div>
        </div>
        <div className="mt-8 text-center text-sm">&copy; 2024 Finance Automation. All rights reserved.</div>
      </footer>
    </div>
  )
}

function BarchartChart(props) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
        className="min-h-[300px]"
      >
        <BarChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
        >
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            tickMargin={10}
            axisLine={false}
            tickFormatter={(value) => value.slice(0, 3)}
          />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Bar dataKey="desktop" fill="var(--color-desktop)" radius={8} />
        </BarChart>
      </ChartContainer>
    </div>
  )
}


function DollarSignIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  )
}


function LinechartChart(props) {
  return (
    <div {...props}>
      <ChartContainer
        config={{
          desktop: {
            label: "Desktop",
            color: "hsl(var(--chart-1))",
          },
        }}
      >
        <LineChart
          accessibilityLayer
          data={[
            { month: "January", desktop: 186 },
            { month: "February", desktop: 305 },
            { month: "March", desktop: 237 },
            { month: "April", desktop: 73 },
            { month: "May", desktop: 209 },
            { month: "June", desktop: 214 },
          ]}
          margin={{
            left: 12,
            right: 12,
          }}
        >
          <CartesianGrid vertical={false} />
          <XAxis
            dataKey="month"
            tickLine={false}
            axisLine={false}
            tickMargin={8}
            tickFormatter={(value) => value.slice(0, 3)}
          />
          <ChartTooltip cursor={false} content={<ChartTooltipContent hideLabel />} />
          <Line dataKey="desktop" type="natural" stroke="var(--color-desktop)" strokeWidth={2} dot={false} />
        </LineChart>
      </ChartContainer>
    </div>
  )
}
