/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HE74Uh4SAYl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Table, TableHeader, TableRow, TableHead, TableBody, TableCell } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"

export function UserDashboard() {
  return (
    <div className="w-full min-h-screen bg-background p-6 md:p-10">
      <div className="mx-auto max-w-6xl">
        <header className="mb-6 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">User Dashboard</h1>
            <p className="text-muted-foreground">Insights and analytics for your user base.</p>
          </div>
          <div className="flex items-center gap-4">
            <Input type="search" placeholder="Search users..." className="max-w-xs" />
            <Button variant="outline">Export Data</Button>
          </div>
        </header>
        <div className="overflow-auto rounded-lg border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Name</TableHead>
                <TableHead>Email</TableHead>
                <TableHead>Signup Date</TableHead>
                <TableHead>Last Login</TableHead>
                <TableHead>Subscription</TableHead>
                <TableHead>Status</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              <TableRow>
                <TableCell className="font-medium">John Doe</TableCell>
                <TableCell className="text-primary">john@example.com</TableCell>
                <TableCell>2023-04-15</TableCell>
                <TableCell>2023-08-12</TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-green-100 text-green-800">
                    Pro
                  </Badge>
                </TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-green-100 text-green-800">
                    Active
                  </Badge>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Jane Smith</TableCell>
                <TableCell className="text-primary">jane@example.com</TableCell>
                <TableCell>2023-01-01</TableCell>
                <TableCell>2023-08-10</TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-yellow-100 text-yellow-800">
                    Basic
                  </Badge>
                </TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-yellow-100 text-yellow-800">
                    Inactive
                  </Badge>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium text-red-500">Michael Johnson</TableCell>
                <TableCell className="text-primary">michael@example.com</TableCell>
                <TableCell>2022-11-30</TableCell>
                <TableCell>2023-08-01</TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-red-100 text-red-800">
                    Cancelled
                  </Badge>
                </TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-red-100 text-red-800">
                    Suspended
                  </Badge>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">Sarah Lee</TableCell>
                <TableCell className="text-primary">sarah@example.com</TableCell>
                <TableCell>2023-03-01</TableCell>
                <TableCell>2023-08-14</TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-green-100 text-green-800">
                    Pro
                  </Badge>
                </TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-green-100 text-green-800">
                    Active
                  </Badge>
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell className="font-medium">David Kim</TableCell>
                <TableCell className="text-primary">david@example.com</TableCell>
                <TableCell>2023-06-01</TableCell>
                <TableCell>2023-08-13</TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-yellow-100 text-yellow-800">
                    Basic
                  </Badge>
                </TableCell>
                <TableCell>
                  <Badge variant="outline" className="bg-yellow-100 text-yellow-800">
                    Inactive
                  </Badge>
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </div>
      </div>
    </div>
  )
}
